apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-15T12:24:48Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "25220"
  uid: bbcf37c7-6aaa-44b7-8a6a-27454703324e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.108.117.133
  clusterIPs:
  - 10.108.117.133
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31888
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
