apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-05-16T05:33:54Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "741"
  uid: 51d0b08d-363a-4b75-bf0c-fb125cd1d022
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.109.64.137
  clusterIPs:
  - 10.109.64.137
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30618
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
